name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install ninja-build libsocketcan-dev libreadline-dev cppcheck -y -qq

    - name: Run cppcheck
      run: |
        mkdir build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -B build
        cppcheck --project=build/compile_commands.json --enable=all --suppress=missingIncludeSystem --suppress=unusedFunction --inconclusive --force --std=c99 --error-exitcode=1

    - name: Build CANvenient
      run: |
        cmake --build build

  Windows:
    needs:   Linux
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Build
        run: |
          cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
